server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://localhost/demo?createDatabaseIfNotExist=true
    username: root
    password: 1234

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework: INFO

